server:
  port: 8080
 
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:guppshupp}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:abc12345}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
           time_zone: GMT+5
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

aws:
  ACCESS_KEY: ${ACCESS_KEY}
  SECRET_KEY: ${SECRET_KEY}